spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  jdbc:mysql://{mysql host}:{mysql port}/{database}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:sonic}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&autoReconnect=true&serverTimezone=GMT%2b8
    # mysql username
    username: ${MYSQL_USERNAME:root}
    # mysql password
    password: ${MYSQL_PASSWORD:Sonic!@#123}
    initialization-mode: always
    schema:
      - classpath:data.sql

mybatis-plus:
  mapper-locations: classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml
  global-config:
    banner: false
  configuration:
    cache-enabled: false
    localCacheScope: STATEMENT
    # sql log
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

actable:
  model:
    pack: org.cloud.sonic.controller.models.domain
  table:
    auto: update
  database:
    type: mysql