# 一般除了修改语言、ldap配置之外，不需要动
sonic:
  token:
    secret: ${SECRET_KEY:sonic}
    expireDay: ${EXPIRE_DAY:14}
  user:
    register:
      enable: ${REGISTER_ENABLE:true}
    normal:
      enable: ${NORMAL_USER_ENABLE:true}
    ldap:
      enable: ${LDAP_USER_ENABLE:true}
      userId: ${LDAP_USER_ID:cn}
      userBaseDN: ${LDAP_BASE_DN:ou=users}

spring:
  ldap:
    base: ${LDAP_BASE:ou=system}
    username: ${LDAP_USERNAME:uid=admin,ou=system}
    password: ${LDAP_PASSWORD:Sonic!@#123}
    urls: ${LDAP_URL:ldap://127.0.0.1:10389}
