version: '3'
services:
  sonic-server-eureka:
    image: "sonicorg/sonic-server-eureka:v1.3.2-release"
    hostname: sonic-server-eureka
    environment:
      - SEC_NAME=sonic #eureka用户名
      - SEC_PASSWORD=sonic #eureka密码
      - EUREKA_HOST=sonic-server-eureka
    volumes:
      - ./logs/:/logs/
    networks:
      - sonic-network
    ports:
      - "9090:9090"
  sonic-server-bus:
    image: "sonicorg/sonic-server-bus:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./config:/config
      - ./logs/:/logs/
    depends_on:
      - sonic-server-eureka
    restart: on-failure
  sonic-server-gateway:
    image: "sonicorg/sonic-server-gateway:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
    ports:
      - "8094:8094"
    restart: on-failure
  sonic-server-controller:
    image: "sonicorg/sonic-server-controller:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    restart: on-failure
  sonic-server-folder:
    image: "sonicorg/sonic-server-folder:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./keepFiles/:/keepFiles/
      - ./imageFiles/:/imageFiles/
      - ./recordFiles/:/recordFiles/
      - ./packageFiles/:/packageFiles/
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    restart: on-failure
  sonic-server-task:
    image: "sonicorg/sonic-server-task:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    restart: on-failure
  sonic-server-transport:
    image: "sonicorg/sonic-server-transport:v1.3.2-release"
    environment:
      - PROFILE=prod
      - EUREKA_URL=http://sonic:sonic@sonic-server-eureka:9090/eureka/
    networks:
      - sonic-network
    volumes:
      - ./logs/:/logs/
    depends_on:
      - sonic-server-bus
      - sonic-server-eureka
      - sonic-server-gateway
    ports:
      - "8095:8095"
    restart: on-failure

networks:
  sonic-network:
    driver: bridge