knife4j:
  enable: true
  setting:
    enableHost: true
    enableHostText: "http://localhost:8094"
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT License | Copyright 2021-[ZhouYiXun/sonic-server](https://github.com/ZhouYixun/sonic-server/blob/main/LICENSE)