server:
  port: 0

spring:
  tomcat:
    max-http-post-size: 100M
  http:
    multipart:
      maxFileSize: 3000M
      maxRequestSize: 3000M
      maxPostSize: 3000M
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1

gateway:
  host: "http://localhost:8094"