server:
  port: 8094

filter:
  white-list: /swagger-resources,/v2/api-docs,/keepFiles/,/imageFiles/,/recordFiles/,/logFiles/

spring:
  cloud:
    gateway:
      routes:
        - id: controller
          uri: lb://sonic-server-controller
          predicates: Path=/api/controller/**
          filters:
            - StripPrefix=2
        - id: folder
          uri: lb://sonic-server-folder
          predicates: Path=/api/folder/**
          filters:
            - StripPrefix=2
        - id: task
          uri: lb://sonic-server-task
          predicates: Path=/api/task/**
          filters:
            - StripPrefix=2