server:
  port: 8092

spring:
  data:
    redis:
      repositories:
        enabled: false

robot:
  client:
    host: "http://localhost:3000"
  img:
    success: ""
    warning: ""
    error: ""