server:
  port: ${SERVER_PORT:9090}

spring:
  version: @project.version@
  application:
    name: @project.artifactId@
    des: "Sonic云真机测试平台 - 注册中心"
  security:
    basic:
      enabled: true
    user:
      name: sonic
      password: tester

eureka:
  datacenter: sonic-server
  environment: prod
  instance:
    hostname: ${EUREKA_HOST:127.0.0.1}
    instance-id: ${spring.application.name}(v${spring.version})-${spring.cloud.client.ip-address}
  client:
    #    单机部署的话放开以下注释
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URL:http://sonic:tester@127.0.0.1:9090/eureka/}

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      max-history: 3

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
