name: deploy to dockerHub

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: replace version
        run: ver=${{ steps.previoustag.outputs.tag }} && new_ver=${ver:1} && sed -i "s/SONIC_VERSION/${new_ver}/g" pom.xml
      - name: login docker hub
        run: echo "${{ secrets.ACCESS_TOKEN_ALIYUN }}" | docker login --username=${{ secrets.ALIYUN_USERNAME }} registry.cn-hongkong.aliyuncs.com --password-stdin
      - name: Validate and Compile with Maven
        run: mvn package
      - name: deploy controller
        run: docker build -t registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-controller:${{ steps.previoustag.outputs.tag }} -f sonic-server-controller/src/main/docker/Dockerfile .
      - name: push controller
        run: docker push registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-controller:${{ steps.previoustag.outputs.tag }}
      - name: deploy eureka
        run: docker build -t registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-eureka:${{ steps.previoustag.outputs.tag }} -f sonic-server-eureka/src/main/docker/Dockerfile .
      - name: push eureka
        run: docker push registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-eureka:${{ steps.previoustag.outputs.tag }}
      - name: deploy gateway
        run: docker build -t registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-gateway:${{ steps.previoustag.outputs.tag }} -f sonic-server-gateway/src/main/docker/Dockerfile .
      - name: push gateway
        run: docker push registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-gateway:${{ steps.previoustag.outputs.tag }}
      - name: deploy folder
        run: docker build -t registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-folder:${{ steps.previoustag.outputs.tag }} -f sonic-server-folder/src/main/docker/Dockerfile .
      - name: push folder
        run: docker push registry.cn-hongkong.aliyuncs.com/sonic-cloud/sonic-server-folder:${{ steps.previoustag.outputs.tag }}
